apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderprocsvc
  labels:
    app: orderprocsvc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orderprocsvc
  template:
    metadata:
      labels:
        app: orderprocsvc
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id:  "orderprocsvc"
        dapr.io/app-port: "6060"
    spec:
      containers:
        - name: orderprocsvc
          image: ko.local/orderprocsvc:latest
          ports:
            - containerPort: 6060
          env:
            - name: APP_PORT
              value: "6060"
            - name: ORDERS_STORE
              value: "orders-store"
            - name: ORDERS_PUBSUB
              value: "orders-pubsub"
            - name: ORDERS_PUBSUB_TOPIC
              value: "received-orders"
            - name: ORDERS_PUBSUB_ROUTE
              value: "/received-orders"

          imagePullPolicy: IfNotPresent