kind: Service
apiVersion: v1
metadata:
  name: ordersvc
  labels:
    app: ordersvc
spec:
  selector:
    app: ordersvc
  ports:
    - name: app-http
      protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 32000
    - name: dapr-http
      port: 3500
      protocol: TCP
      targetPort: 3500
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ordersvc
  labels:
    app: ordersvc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ordersvc
  template:
    metadata:
      labels:
        app: ordersvc
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "ordersvc"
        dapr.io/app-port: "8080"
    spec:
      containers:
        - name: ordersvc
          image: ko.local/ordersvc:latest
          ports:
            - containerPort: 8080
          env:
            - name: APP_ID
              value: ordersvc
            - name: APP_PORT
              value: "8080"
            - name: DAPR_HTTP_PORT
              value: "3500"
          imagePullPolicy: IfNotPresent